-- VHDL Entity proj_master_2025_lib.tb_001_binary_counter.symbol
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 09:44:33 11.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity tb_001_binary_counter is
-- Declarations

end tb_001_binary_counter ;

--
-- VHDL Architecture proj_master_2025_lib.tb_001_binary_counter.struct
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 10:05:46 11.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

library proj_master_2025_lib;

architecture struct of tb_001_binary_counter is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk    : std_logic;
   signal cnt    : std_logic_vector(7 downto 0) := (others => '0');
   signal dir    : std_logic;
   signal enable : std_logic;
   signal reset  : std_logic;


   -- Component Declarations
   component TEST_binary_counter
   generic (
      nbits_g : integer := 8
   );
   port (
      clk    : in     std_logic ;
      reset  : in     std_logic ;
      enable : in     std_logic ;
      dir    : in     std_logic ;
      cnt    : out    std_logic_vector (nbits_g-1 downto 0) := (others => '0')
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : TEST_binary_counter use entity proj_master_2025_lib.TEST_binary_counter;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1   
   -- gen clk signal
   process
   begin
     clk <= '0';
     wait for 5 ns;
     clk <= '1';
     wait for 5 ns;
   end process;
   
   -- gen permanent signals
   process
   begin
    enable <= '0';
    dir <= '1';
    reset <= '1';
   
    wait for 15 ns;
    reset <= '0';
    wait for 10 ns;
    enable <= '1';
   
    wait;
   end process;


   -- Instance port mappings.
   U_0 : TEST_binary_counter
      generic map (
         nbits_g => 8
      )
      port map (
         clk    => clk,
         reset  => reset,
         enable => enable,
         dir    => dir,
         cnt    => cnt
      );

end struct;
