-- VHDL Entity proj_master_2025_lib.tb_006_ANN_02.symbol
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 14:50:32 10.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity tb_006_ANN_02 is
-- Declarations

end tb_006_ANN_02 ;

--
-- VHDL Architecture proj_master_2025_lib.tb_006_ANN_02.struct
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 15:12:32 10.04.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
library proj_master_2025_lib;
use proj_master_2025_lib.p_002_generic_01.all;


architecture struct of tb_006_ANN_02 is

   -- Architecture declarations

   -- Internal signal declarations
   signal ack_RX        : std_logic;
   signal clk           : std_logic;
   signal dst_RX        : std_logic;
   signal layer_accept  : t_array_data_stdlv(0 to 0);
   signal layer_provide : t_array_data_stdlv(0 to 1);
   signal ready_to_TX   : std_logic;
   signal reset         : std_logic;
   signal src_TX        : std_logic;


   -- Component Declarations
   component c_007_mediator
   generic (
      g_layer_length_first : integer           := 4;
      g_layer_length_last  : integer           := 2;
      g_inputs             : t_array2D_integer := ((0,0,0,0),(0,0,0,0))
   );
   port (
      clk           : in     std_logic ;
      reset         : in     std_logic ;
      dst_RX        : in     std_logic ;
      src_TX        : in     std_logic ;
      ready_to_TX   : out    std_logic ;
      ack_RX        : out    std_logic ;
      layer_provide : out    t_array_data_stdlv (0 to g_layer_length_first-1);
      layer_accept  : in     t_array_data_stdlv (0 to g_layer_length_last-1)
   );
   end component;
   component c_x_ANN_01
   port (
      clk         : in     std_logic ;
      reset       : in     std_logic ;
      src_TX      : in     std_logic ;
      ack_RX      : out    std_logic ;
      dst_RX      : in     std_logic ;
      ready_to_TX : out    std_logic ;
      -- layer_in    : in     t_array_data_stdlv (0 to 1);
      -- layer_out   : out    t_array_data_stdlv (0 to 1)
      layer_in    : in     t_array_data_stdlv (0 to 1);
      layer_out   : out    t_array_data_stdlv (0 to 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : c_007_mediator use entity proj_master_2025_lib.c_007_mediator;
   for all : c_x_ANN_01 use entity proj_master_2025_lib.c_x_ANN_01;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1
   -- gen clk signal
   process
   begin
     clk <= '1';
     wait for 5 ns;
     clk <= '0';
     wait for 5 ns;
   end process;

   -- HDL Embedded Text Block 2 eb2
   -- eb2 2
   -- gen permanent signals
   process
   begin
    reset <= '1';
    
    wait for 22 ns;
    reset <= '0';
   
   
    wait;
   end process;


   -- Instance port mappings.
   U_0 : c_007_mediator
      generic map (
         g_layer_length_first => 2,
         g_layer_length_last  => 1,
         g_inputs             => ((20,-20), (128,256), (-128,128), (300,10))
      )
      port map (
         clk           => clk,
         reset         => reset,
         dst_RX        => dst_RX,
         src_TX        => src_TX,
         ready_to_TX   => ready_to_TX,
         ack_RX        => ack_RX,
         layer_provide => layer_provide,
         layer_accept  => layer_accept
      );
   U_1 : c_x_ANN_01
      port map (
         clk         => clk,
         reset       => reset,
         src_TX      => ready_to_TX,
         ack_RX      => dst_RX,
         dst_RX      => ack_RX,
         ready_to_TX => src_TX,
         layer_in    => layer_provide,
         layer_out   => layer_accept
      );

end struct;
