-- VHDL Entity proj_master_2025_lib.tb_002_layer.symbol
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 15:33:32 18.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity tb_002_layer is
-- Declarations

end tb_002_layer ;

--
-- VHDL Architecture proj_master_2025_lib.tb_002_layer.struct
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 11:43:14 21.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
library proj_master_2025_lib;
use proj_master_2025_lib.p_002_generic_01.all;


architecture struct of tb_002_layer is

   -- Architecture declarations

   -- Internal signal declarations
   signal clk         : std_logic;
   --enable      : in     std_logic;
   signal dst_RX      : std_logic;
   signal layer_in    : t_array_data_stdlv(0 to 1);
   signal layer_out   : t_array_data_stdlv(0 to 2);
   signal ready_to_RX : std_logic;
   signal ready_to_TX : std_logic;
   signal reset       : std_logic;
   signal src_TX      : std_logic;


   -- Component Declarations
   component c_004_layer_01
   generic (
      g_layer_length_cur  : integer               := 4;
      g_layer_length_prev : integer               := 2;
      g_layer_bias        : t_array_integer       := (0,0,0,0);
      g_layer_weights     : t_array2D_integer     := ((0,0),(0,0),(0,0),(0,0));
      g_act_func          : t_activation_function := AF_RELU
   );
   port (
      clk         : in     std_logic ;
      reset       : in     std_logic ;
      --enable      : in     std_logic;
      dst_RX      : in     std_logic ;
      src_TX      : in     std_logic ;
      ready_to_TX : out    std_logic ;
      ready_to_RX : out    std_logic ;
      layer_in    : in     t_array_data_stdlv (0 to g_layer_length_prev-1);
      layer_out   : out    t_array_data_stdlv (0 to g_layer_length_cur-1)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : c_004_layer_01 use entity proj_master_2025_lib.c_004_layer_01;
   -- pragma synthesis_on


begin
   -- Architecture concurrent statements
   -- HDL Embedded Text Block 1 eb1
   -- eb1 1
   -- gen clk signal
   process
   begin
     clk <= '1';
     wait for 5 ns;
     clk <= '0';
     wait for 5 ns;
   end process;

   -- HDL Embedded Text Block 2 eb2
   -- eb2 2
   -- gen permanent signals
   process
   begin
    reset <= '1';
    dst_RX <= '0';
    src_TX <= '0';
    
    layer_in(0) <= STD_LOGIC_VECTOR(TO_SIGNED(-269, c_DATA_WIDTH));
    layer_in(1) <= STD_LOGIC_VECTOR(TO_SIGNED(74, c_DATA_WIDTH));
   
    wait for 20 ns;
    reset <= '0';
    wait for 10 ns;
    --enable <= '1';
    src_TX <= '1';
   
    wait;
   end process;


   -- Instance port mappings.
   U_0 : c_004_layer_01
      generic map (
         g_layer_length_cur  => 3,
         g_layer_length_prev => 2,
         g_layer_bias        => (51, 5, 115),
         g_layer_weights     => ((40, 4), (90, -14), (41, 13)),
         g_act_func          => AF_IDENTITY
      )
      port map (
         clk         => clk,
         reset       => reset,
         dst_RX      => dst_RX,
         src_TX      => src_TX,
         ready_to_TX => ready_to_TX,
         ready_to_RX => ready_to_RX,
         layer_in    => layer_in,
         layer_out   => layer_out
      );

end struct;
