-- VHDL Entity proj_master_2025_lib.tb_002_layer.symbol
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 15:33:32 18.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

entity tb_002_layer is
-- Declarations

end tb_002_layer ;

--
-- VHDL Architecture proj_master_2025_lib.tb_002_layer.struct
--
-- Created:
--          by - Admin.UNKNOWN (LAPTOP-7KFJT032)
--          at - 15:37:12 18.03.2025
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2017.1a (Build 5)
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;
library proj_master_2025_lib;
use proj_master_2025_lib.p_002_generic_01.all;


architecture struct of tb_002_layer is

   -- Architecture declarations

   -- Internal signal declarations
   signal address     : std_logic_vector(c_ADDR_WIDTH-1 downto 0);
   signal calc        : std_logic;
   signal clk         : std_logic;
   signal reset       : std_logic;
   signal set_to_bias : std_logic;
   signal val_in      : std_logic_vector(c_DATA_WIDTH-1 downto 0);
   signal val_out     : std_logic_vector(c_DATA_WIDTH-1 downto 0);


   -- Component Declarations
   component c_005_node_01
   generic (
      array_int_bias_weight_g : t_array_integer := (0,1,2,3)
   );
   port (
      address     : in     std_logic_vector (c_ADDR_WIDTH-1 downto 0);
      calc        : in     std_logic;
      clk         : in     std_logic;
      reset       : in     std_logic;
      set_to_bias : in     std_logic;
      val_in      : in     std_logic_vector (c_DATA_WIDTH-1 downto 0);
      val_out     : out    std_logic_vector (c_DATA_WIDTH-1 downto 0)
   );
   end component;

   -- Optional embedded configurations
   -- pragma synthesis_off
   for all : c_005_node_01 use entity proj_master_2025_lib.c_005_node_01;
   -- pragma synthesis_on


begin

   -- Instance port mappings.
   U_0 : c_005_node_01
      generic map (
         array_int_bias_weight_g => (0,1,2,3)
      )
      port map (
         clk         => clk,
         reset       => reset,
         calc        => calc,
         set_to_bias => set_to_bias,
         address     => address,
         val_in      => val_in,
         val_out     => val_out
      );

end struct;
